# Generated by Django 5.2.15 on 2026-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('disposition', models.CharField(choices=[('PROMISE_TO_PAY', 'Promise to Pay'), ('NOT_REACHABLE', 'Not Reachable'), ('WRONG_NUMBER', 'Wrong Number'), ('REFUSED_TO_PAY', 'Refused to Pay'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('FULL_PAYMENT', 'Full Payment'), ('CALL_BACK', 'Call Back Later'), ('OTHER', 'Other')], max_length=20)),
                ('next_call_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_type', models.CharField(choices=[('CALL', 'Phone Call'), ('FIELD', 'Field Visit')], max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
