# Generated by Django 5.2.15 on 2026-06-09 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='customers.customer'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['customer', 'created_at'], name='interaction_custome_01a079_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['disposition'], name='interaction_disposi_e29281_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['created_by'], name='interaction_created_91106f_idx'),
        ),
    ]
