# Generated by Django 5.2.15 on 2026-06-09 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('interactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='collection_officer',
            field=models.ForeignKey(limit_choices_to={'role': 'COLLECTION_OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='latest_interaction',
            field=models.ForeignKey(blank=True, help_text='Reference to the most recent interaction with this customer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interactions.interaction'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['collection_officer'], name='customers_c_collect_61acc3_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['latest_interaction'], name='customers_c_latest__be2e41_idx'),
        ),
    ]
