# Generated by Django 5.2.15 on 2026-06-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=36, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('query_params', models.JSONField(blank=True, null=True)),
                ('request_data', models.JSONField(blank=True, null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('execution_time', models.FloatField(null=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('is_error', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['request_id'], name='logger_apil_request_d4704b_idx'), models.Index(fields=['endpoint'], name='logger_apil_endpoin_0186ed_idx'), models.Index(fields=['timestamp'], name='logger_apil_timesta_90191e_idx'), models.Index(fields=['user'], name='logger_apil_user_c91dd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user', models.CharField(max_length=255)),
                ('action', models.TextField()),
                ('level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='logger_user_user_aa3436_idx'), models.Index(fields=['user_id'], name='logger_user_user_id_500f77_idx'), models.Index(fields=['timestamp'], name='logger_user_timesta_2838d3_idx')],
            },
        ),
    ]
